package com.aistudyhub.common.enums;

public enum ActivityActionType {
    LOGIN,
    LOGOUT,
    UPLOAD_DOCUMENT,
    DELETE_DOCUMENT,
    DOWNLOAD_DOCUMENT,
    PUBLISH_MARKETPLACE,
    REVIEW_CONTENT,
    REPORT_CONTENT,
    RESOLVE_REPORT,
    CHAT_AI,
    GENERATE_QUIZ,
    GENERATE_FLASHCARD,
    UPDATE_SYSTEM_CONFIG,
    UPDATE_DOCUMENT_SAFETY_SETTINGS,
    DOCUMENT_SAFETY_REVIEW_CREATED,
    APPROVE_DOCUMENT_SAFETY,
    REJECT_DOCUMENT_SAFETY,
    GRANT_COMMUNITY_ROLE,
    REVOKE_COMMUNITY_ROLE
}
