package com.aistudyhub.common.enums;

public enum ActivityActionType {
    LOGIN,
    LOGOUT,
    UPLOAD_DOCUMENT,
    DELETE_DOCUMENT,
    DOWNLOAD_DOCUMENT,
    PUBLISH_MARKETPLACE,
    REVIEW_CONTENT,
    REPORT_CONTENT,
    RESOLVE_REPORT,
    CHAT_AI,
    GENERATE_QUIZ,
    GENERATE_FLASHCARD,
    UPDATE_SYSTEM_CONFIG,
    GRANT_COMMUNITY_ROLE,
    REVOKE_COMMUNITY_ROLE
}
