package com.aistudyhub.common.enums;

public enum ReputationEventType {
    CONTENT_APPROVED_DOCUMENT,
    CONTENT_APPROVED_QUIZ,
    CONTENT_APPROVED_FLASHCARD_DECK,
    MARKETPLACE_CLONE_RECEIVED,
    CONTENT_DOWNLOAD_MILESTONE,
    COMMUNITY_REVIEW_GOOD,
    COMMUNITY_REVIEW_BAD,
    REVIEWER_MARKETPLACE_VOTE,
    REVIEWER_DECISION_ALIGNED,
    CONTENT_REPORT_ACCEPTED,
    CONTENT_REPORT_REJECTED,
    CONTENT_REPORT_OWNER_PENALTY,
    CONTENT_HIDDEN_PENALTY
}
