package com.aistudyhub.module.systemconfig;

import java.util.Set;

/**
 * Canonical system config keys dùng chung giữa các module.
 */
public final class SystemConfigKeys {

    public static final String MAX_UPLOAD_FILE_SIZE_BYTES = "MAX_UPLOAD_FILE_SIZE_BYTES";
    public static final String ALLOWED_FILE_TYPES = "ALLOWED_FILE_TYPES";
    public static final String BASE_REPUTATION_PER_UPLOAD = "BASE_REPUTATION_PER_UPLOAD";
    public static final String MARKETPLACE_AUTO_APPROVE_MIN_REVIEWS = "MARKETPLACE_AUTO_APPROVE_MIN_REVIEWS";
    public static final String MARKETPLACE_AUTO_APPROVE_ACCEPT_PERCENTAGE =
            "MARKETPLACE_AUTO_APPROVE_ACCEPT_PERCENTAGE";
    public static final String FREE_DOWNLOAD_WAIT_SECONDS = "FREE_DOWNLOAD_WAIT_SECONDS";
    public static final String PRO_COMMISSION_PERCENTAGE = "PRO_COMMISSION_PERCENTAGE";
    public static final String AI_CHAT_DAILY_LIMIT = "AI_CHAT_DAILY_LIMIT";
    public static final String AI_SUMMARY_DAILY_LIMIT = "AI_SUMMARY_DAILY_LIMIT";
    public static final String RESET_TOKEN_EXPIRE_MINUTES = "RESET_TOKEN_EXPIRE_MINUTES";
    public static final String GROWTH_REFERRAL_REWARD_POINTS = "GROWTH_REFERRAL_REWARD_POINTS";
    public static final String GROWTH_TOP_CONTRIBUTOR_LIMIT = "GROWTH_TOP_CONTRIBUTOR_LIMIT";
    public static final String GROWTH_REFERRAL_AMBASSADOR_INVITES = "GROWTH_REFERRAL_AMBASSADOR_INVITES";
    public static final String REWARD_MARKETPLACE_CONTRIBUTOR_APPROVED_CONTENTS =
            "REWARD_MARKETPLACE_CONTRIBUTOR_APPROVED_CONTENTS";
    public static final String REWARD_POPULAR_CREATOR_DOWNLOADS = "REWARD_POPULAR_CREATOR_DOWNLOADS";
    public static final String REWARD_TOP_REVIEWER_REVIEWS = "REWARD_TOP_REVIEWER_REVIEWS";
    public static final String REWARD_REPUTATION_MILESTONE_POINTS = "REWARD_REPUTATION_MILESTONE_POINTS";
    public static final String COMMUNITY_MODERATOR_NOMINATION_LIMIT_PER_SUBJECT =
            "COMMUNITY_MODERATOR_NOMINATION_LIMIT_PER_SUBJECT";
    public static final String COMMUNITY_REVIEWER_ELIGIBLE_POINTS = "COMMUNITY_REVIEWER_ELIGIBLE_POINTS";
    public static final String COMMUNITY_REVIEWER_NOMINATION_LIMIT_PER_SUBJECT =
            "COMMUNITY_REVIEWER_NOMINATION_LIMIT_PER_SUBJECT";

    public static final Set<String> PUBLIC_KEYS = Set.of(
            MAX_UPLOAD_FILE_SIZE_BYTES,
            ALLOWED_FILE_TYPES,
            FREE_DOWNLOAD_WAIT_SECONDS,
            AI_CHAT_DAILY_LIMIT,
            AI_SUMMARY_DAILY_LIMIT
    );

    public static final Set<String> NON_NEGATIVE_INTEGER_KEYS = Set.of(
            GROWTH_REFERRAL_REWARD_POINTS,
            GROWTH_TOP_CONTRIBUTOR_LIMIT,
            GROWTH_REFERRAL_AMBASSADOR_INVITES,
            REWARD_MARKETPLACE_CONTRIBUTOR_APPROVED_CONTENTS,
            REWARD_POPULAR_CREATOR_DOWNLOADS,
            REWARD_TOP_REVIEWER_REVIEWS,
            REWARD_REPUTATION_MILESTONE_POINTS,
            COMMUNITY_MODERATOR_NOMINATION_LIMIT_PER_SUBJECT,
            COMMUNITY_REVIEWER_ELIGIBLE_POINTS,
            COMMUNITY_REVIEWER_NOMINATION_LIMIT_PER_SUBJECT
    );

    private SystemConfigKeys() {
    }
}
